######################################################################
# Automatically generated by qmake (2.01a) Mi. Aug 10 13:08:18 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Taschenrechner.h
FORMS += Taschenrechner.ui
SOURCES += main.cpp Taschenrechner.cpp
